export const SET_FILTER = 'SET_FILTER';
export const SET_SORTING = 'SET_SORTING';

export const GET_SEARCH_ID = 'GET_SEARCH_ID';

export const GET_PACK_OF_TICKETS = 'GET_PACK_OF_TICKETS';
export const SET_SORTING_TICKETS = 'SET_SORTING_TICKETS';

export const SET_STOP_GETTING_TICKETS = 'SET_STOP_GETTING_TICKETS';

export const ADD_TICKETS_COUNT = 'ADD_TICKETS_COUNT';
export const RESET_TICKETS_COUNT = 'RESET_TICKETS_COUNT';

export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';
