export const SET_FILTER = 'SET_FILTER';
export const SET_SORTING = 'SET_SORTING';

export const GET_SEARCH_ID = 'GET_SEARCH_ID';
export const GET_PACK_OF_TICKETS = 'GET_PACK_OF_TICKETS';
export const SET_STOP_GETTING_TICKETS = 'SET_STOP_GETTING_TICKETS';

export const SORT_CHEAPEST = 'SORT_CHEAPEST';
export const SORT_FASTEST = 'SORT_FASTEST';
export const SORT_OPTIMAL = 'SORT_OPTIMAL';

export const TOGGLE_SPINNER = 'TOGGLE_SPINNER';
