export const FILTERS = {
  ALL: 'ALL',
  WITHOUT_TRANSFERS: 'WITHOUT_TRANSFERS',
  ONE_TRANSFER: 'ONE_TRANSFER',
  TWO_TRANSFERS: 'TWO_TRANSFERS',
  THREE_TRANSFERS: 'THREE_TRANSFERS',
};

export const SORTING = {
  CHEAPEST: 'CHEAPEST',
  FASTEST: 'FASTEST',
  OPTIMAL: 'OPTIMAL',
};
